from typing import Optional
from enum import Enum
from pydantic import BaseModel, Field, model_validator

class PokemonType(Enum):
    NORMAL = "normal"
    FIRE = "fire"
    WATER = "water"
    ELECTRIC = "electric"
    GRASS = "grass"
    ICE = "ice"
    FIGHTING = "fighting"
    POISON = "poison"
    GROUND = "ground"
    FLYING = "flying"
    PSYCHIC = "psychic"
    BUG = "bug"
    ROCK = "rock"
    GHOST = "ghost"
    DRAGON = "dragon"
    DARK = "dark"
    STEEL = "steel"
    FAIRY = "fairy"

class StatusCondition(Enum):
    NONE = "none"
    PARALYSIS = "paralysis"
    POISON = "poison"
    BURN = "burn"
    FREEZE = "freeze"
    SLEEP = "sleep"
    TRAP = "trap"
    CONFUSION = "confusion"
    DISABLE = "disable"
    FLINCH = "flinch"
    LEECH_SEED = "leech_seed"
    UNKNOWN = "unknown"
    NIGHTMARE = "nightmare"
    NO_TYPE_IMMUNITY = "no_type_immunity"
    PERISH_SONG = "perish_song"
    INFATUATION = "infatuation"
    TORMENT = "torment"
    CURSE = "curse"
    INGRAIN = "ingrain"
    HEAL_BLOCK = "heal_block"
    YAWN = "yawn"
    EMBARGO = "embargo"
    SILENCE = "silence"
    TAR_SHOT = "tar_shot"