# Auto-generated from pokeapi_database/type/*.json
# Do not edit by hand. Regenerate via tools/generate_type_chart.py

from typing import Mapping
from shared.pokemon.types import PokemonType

TYPE_EFFECTIVENESS: Mapping[PokemonType, dict[PokemonType, float]] = {
    PokemonType.NORMAL: {
        PokemonType.GHOST: 0.0,
        PokemonType.ROCK: 0.5,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.FIRE: {
        PokemonType.BUG: 2.0,
        PokemonType.DRAGON: 0.5,
        PokemonType.FIRE: 0.5,
        PokemonType.GRASS: 2.0,
        PokemonType.ICE: 2.0,
        PokemonType.ROCK: 0.5,
        PokemonType.STEEL: 2.0,
        PokemonType.WATER: 0.5,
    },
    PokemonType.WATER: {
        PokemonType.DRAGON: 0.5,
        PokemonType.FIRE: 2.0,
        PokemonType.GRASS: 0.5,
        PokemonType.GROUND: 2.0,
        PokemonType.ROCK: 2.0,
        PokemonType.WATER: 0.5,
    },
    PokemonType.ELECTRIC: {
        PokemonType.DRAGON: 0.5,
        PokemonType.ELECTRIC: 0.5,
        PokemonType.FLYING: 2.0,
        PokemonType.GRASS: 0.5,
        PokemonType.GROUND: 0.0,
        PokemonType.WATER: 2.0,
    },
    PokemonType.GRASS: {
        PokemonType.BUG: 0.5,
        PokemonType.DRAGON: 0.5,
        PokemonType.FIRE: 0.5,
        PokemonType.FLYING: 0.5,
        PokemonType.GRASS: 0.5,
        PokemonType.GROUND: 2.0,
        PokemonType.POISON: 0.5,
        PokemonType.ROCK: 2.0,
        PokemonType.STEEL: 0.5,
        PokemonType.WATER: 2.0,
    },
    PokemonType.ICE: {
        PokemonType.DRAGON: 2.0,
        PokemonType.FIRE: 0.5,
        PokemonType.FLYING: 2.0,
        PokemonType.GRASS: 2.0,
        PokemonType.GROUND: 2.0,
        PokemonType.ICE: 0.5,
        PokemonType.STEEL: 0.5,
        PokemonType.WATER: 0.5,
    },
    PokemonType.FIGHTING: {
        PokemonType.BUG: 0.5,
        PokemonType.DARK: 2.0,
        PokemonType.FAIRY: 0.5,
        PokemonType.FLYING: 0.5,
        PokemonType.GHOST: 0.0,
        PokemonType.ICE: 2.0,
        PokemonType.NORMAL: 2.0,
        PokemonType.POISON: 0.5,
        PokemonType.PSYCHIC: 0.5,
        PokemonType.ROCK: 2.0,
        PokemonType.STEEL: 2.0,
    },
    PokemonType.POISON: {
        PokemonType.FAIRY: 2.0,
        PokemonType.GHOST: 0.5,
        PokemonType.GRASS: 2.0,
        PokemonType.GROUND: 0.5,
        PokemonType.POISON: 0.5,
        PokemonType.ROCK: 0.5,
        PokemonType.STEEL: 0.0,
    },
    PokemonType.GROUND: {
        PokemonType.BUG: 0.5,
        PokemonType.ELECTRIC: 2.0,
        PokemonType.FIRE: 2.0,
        PokemonType.FLYING: 0.0,
        PokemonType.GRASS: 0.5,
        PokemonType.POISON: 2.0,
        PokemonType.ROCK: 2.0,
        PokemonType.STEEL: 2.0,
    },
    PokemonType.FLYING: {
        PokemonType.BUG: 2.0,
        PokemonType.ELECTRIC: 0.5,
        PokemonType.FIGHTING: 2.0,
        PokemonType.GRASS: 2.0,
        PokemonType.ROCK: 0.5,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.PSYCHIC: {
        PokemonType.DARK: 0.0,
        PokemonType.FIGHTING: 2.0,
        PokemonType.POISON: 2.0,
        PokemonType.PSYCHIC: 0.5,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.BUG: {
        PokemonType.DARK: 2.0,
        PokemonType.FAIRY: 0.5,
        PokemonType.FIGHTING: 0.5,
        PokemonType.FIRE: 0.5,
        PokemonType.FLYING: 0.5,
        PokemonType.GHOST: 0.5,
        PokemonType.GRASS: 2.0,
        PokemonType.POISON: 0.5,
        PokemonType.PSYCHIC: 2.0,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.ROCK: {
        PokemonType.BUG: 2.0,
        PokemonType.FIGHTING: 0.5,
        PokemonType.FIRE: 2.0,
        PokemonType.FLYING: 2.0,
        PokemonType.GROUND: 0.5,
        PokemonType.ICE: 2.0,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.GHOST: {
        PokemonType.DARK: 0.5,
        PokemonType.GHOST: 2.0,
        PokemonType.NORMAL: 0.0,
        PokemonType.PSYCHIC: 2.0,
    },
    PokemonType.DRAGON: {
        PokemonType.DRAGON: 2.0,
        PokemonType.FAIRY: 0.0,
        PokemonType.STEEL: 0.5,
    },
    PokemonType.DARK: {
        PokemonType.DARK: 0.5,
        PokemonType.FAIRY: 0.5,
        PokemonType.FIGHTING: 0.5,
        PokemonType.GHOST: 2.0,
        PokemonType.PSYCHIC: 2.0,
    },
    PokemonType.STEEL: {
        PokemonType.ELECTRIC: 0.5,
        PokemonType.FAIRY: 2.0,
        PokemonType.FIRE: 0.5,
        PokemonType.ICE: 2.0,
        PokemonType.ROCK: 2.0,
        PokemonType.STEEL: 0.5,
        PokemonType.WATER: 0.5,
    },
    PokemonType.FAIRY: {
        PokemonType.DARK: 2.0,
        PokemonType.DRAGON: 2.0,
        PokemonType.FIGHTING: 2.0,
        PokemonType.FIRE: 0.5,
        PokemonType.POISON: 0.5,
        PokemonType.STEEL: 0.5,
    },
}
